/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author jhoar
 */
public class Forma06 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Forma06
     */
    public Forma06() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtBuscarCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtCodigoCita = new javax.swing.JTextField();
        txtNombreMascota = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtServicioCita = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtFechaCita = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPersonalCita = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnInfoMascota = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaMedicinas = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaDiagnostico = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txaRecomendaciones = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txaRecetas = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();
        btnCitaAtendida = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaResumenCita = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscarCodigo.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscarCodigo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtBuscarCodigo.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscarCodigo.setToolTipText("");
        txtBuscarCodigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 183, 183), 1, true));
        jPanel2.add(txtBuscarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Código de la Cita");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(0, 183, 183));
        btnBuscar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("ATENDER");
        btnBuscar.setBorder(null);
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 100, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 80));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodigoCita.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoCita.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCodigoCita.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigoCita.setToolTipText("");
        txtCodigoCita.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 183, 183), 1, true));
        jPanel3.add(txtCodigoCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, 40));

        txtNombreMascota.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreMascota.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNombreMascota.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreMascota.setToolTipText("");
        txtNombreMascota.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 183, 183), 1, true));
        jPanel3.add(txtNombreMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 180, 40));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Servicio");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        txtServicioCita.setBackground(new java.awt.Color(255, 255, 255));
        txtServicioCita.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtServicioCita.setForeground(new java.awt.Color(0, 0, 0));
        txtServicioCita.setToolTipText("");
        txtServicioCita.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 183, 183), 1, true));
        jPanel3.add(txtServicioCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 260, 40));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Fecha y Hora");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        txtFechaCita.setBackground(new java.awt.Color(255, 255, 255));
        txtFechaCita.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtFechaCita.setForeground(new java.awt.Color(0, 0, 0));
        txtFechaCita.setToolTipText("");
        txtFechaCita.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 183, 183), 1, true));
        jPanel3.add(txtFechaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 130, 40));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Nombre del Cliente");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        txtNombreCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreCliente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNombreCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreCliente.setToolTipText("");
        txtNombreCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 183, 183), 1, true));
        jPanel3.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 260, 40));

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Personal");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        txtPersonalCita.setBackground(new java.awt.Color(255, 255, 255));
        txtPersonalCita.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtPersonalCita.setForeground(new java.awt.Color(0, 0, 0));
        txtPersonalCita.setToolTipText("");
        txtPersonalCita.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 183, 183), 1, true));
        jPanel3.add(txtPersonalCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 260, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Información de la Cita");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Nombre de la Mascota");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Código");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        btnInfoMascota.setBackground(new java.awt.Color(0, 183, 183));
        btnInfoMascota.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnInfoMascota.setForeground(new java.awt.Color(255, 255, 255));
        btnInfoMascota.setText("INFO");
        btnInfoMascota.setBorder(null);
        btnInfoMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoMascotaActionPerformed(evt);
            }
        });
        jPanel3.add(btnInfoMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 70, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 280, 370));

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Diagnóstico");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Recomendaciones");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Medicinas");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Receta");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setHorizontalScrollBar(null);

        txaMedicinas.setBackground(new java.awt.Color(255, 255, 255));
        txaMedicinas.setColumns(20);
        txaMedicinas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txaMedicinas.setRows(5);
        txaMedicinas.setBorder(null);
        jScrollPane3.setViewportView(txaMedicinas);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 280, 70));

        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setHorizontalScrollBar(null);

        txaDiagnostico.setBackground(new java.awt.Color(255, 255, 255));
        txaDiagnostico.setColumns(20);
        txaDiagnostico.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txaDiagnostico.setRows(5);
        txaDiagnostico.setBorder(null);
        jScrollPane4.setViewportView(txaDiagnostico);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 280, 70));

        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane5.setHorizontalScrollBar(null);

        txaRecomendaciones.setBackground(new java.awt.Color(255, 255, 255));
        txaRecomendaciones.setColumns(20);
        txaRecomendaciones.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txaRecomendaciones.setRows(5);
        txaRecomendaciones.setBorder(null);
        jScrollPane5.setViewportView(txaRecomendaciones);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 280, 70));

        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane6.setHorizontalScrollBar(null);

        txaRecetas.setBackground(new java.awt.Color(255, 255, 255));
        txaRecetas.setColumns(20);
        txaRecetas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txaRecetas.setRows(5);
        txaRecetas.setBorder(null);
        jScrollPane6.setViewportView(txaRecetas);

        jPanel4.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 280, 70));

        btnLimpiar.setBackground(new java.awt.Color(0, 183, 183));
        btnLimpiar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(null);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel4.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 130, 40));

        btnCitaAtendida.setBackground(new java.awt.Color(0, 183, 183));
        btnCitaAtendida.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCitaAtendida.setForeground(new java.awt.Color(255, 255, 255));
        btnCitaAtendida.setText("CITA ATENDIDA");
        btnCitaAtendida.setBorder(null);
        btnCitaAtendida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitaAtendidaActionPerformed(evt);
            }
        });
        jPanel4.add(btnCitaAtendida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 130, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 300, 460));

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txaResumenCita.setBackground(new java.awt.Color(255, 255, 255));
        txaResumenCita.setColumns(20);
        txaResumenCita.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txaResumenCita.setForeground(new java.awt.Color(0, 0, 0));
        txaResumenCita.setRows(5);
        txaResumenCita.setBorder(null);
        jScrollPane1.setViewportView(txaResumenCita);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 310, 420));

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Resumen Cita");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 330, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnInfoMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInfoMascotaActionPerformed

    private void btnCitaAtendidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitaAtendidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCitaAtendidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnCitaAtendida;
    public javax.swing.JButton btnInfoMascota;
    public javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JTextArea txaDiagnostico;
    public javax.swing.JTextArea txaMedicinas;
    public javax.swing.JTextArea txaRecetas;
    public javax.swing.JTextArea txaRecomendaciones;
    public javax.swing.JTextArea txaResumenCita;
    public javax.swing.JTextField txtBuscarCodigo;
    public javax.swing.JTextField txtCodigoCita;
    public javax.swing.JTextField txtFechaCita;
    public javax.swing.JTextField txtNombreCliente;
    public javax.swing.JTextField txtNombreMascota;
    public javax.swing.JTextField txtPersonalCita;
    public javax.swing.JTextField txtServicioCita;
    // End of variables declaration//GEN-END:variables
}
